version: "3"
services:
  solr:
    image: ghcr.io/datagov-cz/nkod-solr:latest  
    build: 
      context: ../solr
    ports:
      - 8983:8983
    restart: always
    volumes:
      - solr-cores:/var/solr
volumes:
  solr-cores:
    name: nkod-solr-cores
    external: True
